version: '1.0'
metadata:
  generated_by: random_config_exclusion
  percentage: 0.0
  random_seed: 42
  timestamp: '2026-09-03T22:55:41.760625'
  total_tuples: 400
  total_rules: 0
settings:
  apply_to_train: true
  apply_to_val: true
  apply_to_test: false
exclusions: []
